### ISSUE TITLE
Why do you need Redis as a session store?

### ISSUE THREAD

**Issue by ccnokes** [dwyl/hapi-auth-jwt2-example#13]
I'm trying to understand why you would need Redis as a session store. According to Auth0, one benefit of using JWTs is that you don't _need_ one (although you could optionally have one if you wanted to store additional information on the user). It seems like if the JWT is signed and then can be decoded, it must be valid -- no need to verify if the server also has a corresponding entry for it in it's store. But maybe I'm missing something? 

See https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/
"There is no need to keep a session store, the token is a self-contained entity that conveys all the user information. The rest of the state lives in cookies or local storage on the client side."

**Comment by nelsonic** [comment]
@ccnokes great question. Redis session store is not required. _Ideally_ your app would be stateless and all the necessary info would be contained within the `JWT`, however we have chose to only keep the _minimum_ info in the `JWT` and store session in Redis for an important reason not covered in the auth0 article: how do you _invalidate_ a JWT...?
Unless you have an `exp` (_expiry_) baked into the `JWT` the token is valid _for ever_...
If we store the _details_ of the session in Redis it becomes _easy_ to provide "Log Out" in our app.

But, again, this is a matter of preference in architecture. Redis is _rarely_ (_if ever_) the bottleneck in our app(s) because its so fast, but if you want to be _truly_ stateless then store all session info in the `JWT` and avoid hitting the database for every request. :+1:

**Comment by ccnokes** [comment]
Thanks @nelsonic, great answer--that clears up my question. I appreciate the examples and explanations dwyl provides, they've been helpful :smile_cat:
